import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

import styles from '../styles/Home.module.css'
import { ipfsGateway } from '../ipfs-gateway'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image
          src={ipfsGateway.getLocalGatewayUrl(
            'ipfs://bafkreiab33ip5asyevt6pr3cx56nd4373zaeme6qbqt6f5p2q53hfl6smi',
          )}
          width={500}
          height={500}
          objectFit="contain"
          alt="With Vercel's Image Optimization"
        />

        {/* eslint-disable-next-line @next/next/no-img-element */}
        <img
          src={ipfsGateway.getLocalGatewayUrl(
            'ipfs://bafkreiab33ip5asyevt6pr3cx56nd4373zaeme6qbqt6f5p2q53hfl6smi',
          )}
          alt="With Service Worker Gateway"
        />
      </main>
    </div>
  )
}

export default Home
